spring.application.name=Lumiere
spring.datasource.url=jdbc:postgresql://ep-xxxx.region.aws.neon.tech/lumiere-db?sslmode=require
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true