-- =====================================================================
-- Lumière — V1 initial schema (Flyway migration)
-- PostgreSQL
--
-- This migration creates the 6 core tables for Lumière V1:
--   category, product, product_image, orders, order_item, customer_info
--
-- Notes:
--   * order.status is VARCHAR + CHECK (not a Postgres ENUM type) so it maps
--     cleanly to Spring Boot @Enumerated(EnumType.STRING) and is easy to
--     extend in a later migration.
--   * Products are never hard-deleted while linked to orders; they are
--     hidden with is_active = false (soft delete).
--   * A product is "on sale" when sale_price IS NOT NULL AND sale_price < price
--     (computed at read time, never stored).
--   * Product images live only in product_image. The image with the lowest
--     display_order (0) is the main image. There is NO image_url on product.
--   * order_item.unit_price is the price FROZEN at purchase time and never
--     changes afterwards, even if the product price changes later.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. category
-- ---------------------------------------------------------------------
CREATE TABLE category (
                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name        VARCHAR(100) NOT NULL,
                          slug        VARCHAR(120) NOT NULL UNIQUE,
                          cover_image VARCHAR(500),
                          created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Reserved slugs ('all', 'sale') are blocked in the backend, not here,
-- because they conflict with the /shop/all and /shop/sale routes.


-- ---------------------------------------------------------------------
-- 2. product
-- ---------------------------------------------------------------------
CREATE TABLE product (
                         id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         category_id    BIGINT        NOT NULL REFERENCES category(id),
                         name           VARCHAR(150)  NOT NULL,
                         slug           VARCHAR(180)  NOT NULL UNIQUE,
                         description    TEXT,
                         price          DECIMAL(10,2) NOT NULL,
                         sale_price     DECIMAL(10,2),
                         material       VARCHAR(100),
                         size           VARCHAR(50),
                         chain_length   VARCHAR(50),
                         stock_quantity INT           NOT NULL DEFAULT 0,
                         display_order  INT           NOT NULL DEFAULT 0,
                         is_active      BOOLEAN       NOT NULL DEFAULT TRUE,
                         created_at     TIMESTAMP     NOT NULL DEFAULT NOW(),
                         updated_at     TIMESTAMP     NOT NULL DEFAULT NOW(),

                         CONSTRAINT chk_product_price_positive     CHECK (price > 0),
                         CONSTRAINT chk_product_sale_price_valid   CHECK (sale_price IS NULL OR sale_price < price),
                         CONSTRAINT chk_product_stock_non_negative CHECK (stock_quantity >= 0)
);

CREATE INDEX idx_product_category ON product(category_id);
CREATE INDEX idx_product_active    ON product(is_active);


-- ---------------------------------------------------------------------
-- 3. product_image
-- ---------------------------------------------------------------------
CREATE TABLE product_image (
                               id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               product_id    BIGINT        NOT NULL REFERENCES product(id) ON DELETE CASCADE,
                               image_url     VARCHAR(500)  NOT NULL,
                               display_order INT           NOT NULL DEFAULT 0
);

CREATE INDEX idx_product_image_product ON product_image(product_id);


-- ---------------------------------------------------------------------
-- 4. orders   (plural: "order" is a reserved SQL keyword)
-- ---------------------------------------------------------------------
CREATE TABLE orders (
                        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_number    VARCHAR(30)   NOT NULL UNIQUE,
                        status          VARCHAR(30)   NOT NULL,
                        total_amount    DECIMAL(10,2) NOT NULL,
                        deposit_amount  DECIMAL(10,2) NOT NULL,
                        deposit_paid_at TIMESTAMP,
                        confirmed_at    TIMESTAMP,
                        created_at      TIMESTAMP     NOT NULL DEFAULT NOW(),

                        CONSTRAINT chk_orders_status CHECK (status IN (
                                                                       'PENDING_DEPOSIT',
                                                                       'DEPOSIT_UNDER_REVIEW',
                                                                       'CONFIRMED',
                                                                       'PREPARING',
                                                                       'SHIPPED',
                                                                       'DELIVERED',
                                                                       'CANCELLED',
                                                                       'DEPOSIT_REJECTED'
                            )),
                        CONSTRAINT chk_orders_total_positive       CHECK (total_amount > 0),
                        CONSTRAINT chk_orders_deposit_non_negative CHECK (deposit_amount >= 0)
);

CREATE INDEX idx_orders_status ON orders(status);


-- ---------------------------------------------------------------------
-- 5. order_item
-- ---------------------------------------------------------------------
CREATE TABLE order_item (
                            id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id   BIGINT        NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
                            product_id BIGINT        NOT NULL REFERENCES product(id),
                            quantity   INT           NOT NULL,
                            unit_price DECIMAL(10,2) NOT NULL,

                            CONSTRAINT chk_order_item_quantity   CHECK (quantity > 0),
                            CONSTRAINT chk_order_item_unit_price CHECK (unit_price > 0)
);

CREATE INDEX idx_order_item_order   ON order_item(order_id);
CREATE INDEX idx_order_item_product ON order_item(product_id);


-- ---------------------------------------------------------------------
-- 6. customer_info   (one-to-one with orders via UNIQUE order_id)
-- ---------------------------------------------------------------------
CREATE TABLE customer_info (
                               id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               order_id    BIGINT       NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
                               full_name   VARCHAR(150) NOT NULL,
                               phone       VARCHAR(20)  NOT NULL,
                               governorate VARCHAR(50)  NOT NULL,
                               address     TEXT         NOT NULL,
                               notes       TEXT
);

CREATE INDEX idx_customer_info_phone ON customer_info(phone);